### ISSUE TITLE
Getting weird numbers 

### ISSUE THREAD

**Issue by weidi** [ReverseEngineeringDE/SAIC-API-Documentation#13]
![Screenshot_20230103-181721.png](https://user-images.githubusercontent.com/2188062/210408018-9e45d56a-f4b4-45ef-bc7c-38f83c32db35.png)

Shows 102 % soc and thus all other related values not plausible.

SOC at this time was 34%

**Comment by dajpereira** [comment]
Can you explain or do a small tutorial explaining how to integrate in HA?

**Comment by ReverseEngineeringDE** [comment]
> Can you explain or do a small tutorial explaining how to integrate in HA?

Take a look at: https://github.com/ReverseEngineeringDE/iSmart-Gateway-Home-Assistant-Add-on

**Comment by ReverseEngineeringDE** [comment]
Maybe we should switch to the new MQTT package? Seems to be more reliable for a HA integration.

Also I need to update the readme of this project....

**Comment by weidi** [comment]
MQTT is for sure the better shot and I like the implementation and how its done with rtl_433.
On the other hand a "pure" REST Integration would be more flexible and less overhead for a quickstart but i dont know python so i cannot help here.

**Comment by tisoft** [comment]
Do you mean the environment variables to configure the MQTT gateway?

If so you might want to try the new docker image I have created. Sample docker compose file:
```yaml
version: "3.9"
services:
  ismart_mqtt:
    image: "tisoft/ismart-mqtt-gateway:docker_build-latest"
    environment:
      SAIC_USER: your.email@example.com
      SAIC_PASSWORD: YourPassword
      MQTT_URI: ws://test.mosquitto.org:8080
```

**Comment by weidi** [comment]
I am playing with a HomeAssistant Addon config.yaml like so but the java binary doesnt seem to pick all of them up

```yaml
---
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
description: "SAIC MQTT Gateway"
name: "SAIC MQTT"
slug: saic_mqtt
version: "0.0.14"
init: false
environment:
  MQTT_URI: "mqtt://192.168.3.2:1883"
  MQTT_PASSWORD: "mqtt"
  MQTT_USER: "mqtt123"
  SAIC_PASSWORD: "asdfasdf"
  SAIC_USER: "asdfasdf@asdf.com"
  ABRP_USER_TOKEN: ""
  ABRP_API_KEY: ""
```

```Dockerfile
ARG BUILD_FROM
FROM $BUILD_FROM

RUN apk add --no-cache openjdk17-jre-headless
WORKDIR /
ADD ismart-mqtt-gateway-0.0.3-full.jar ismart-mqtt-gateway.jar
CMD ["java","-jar","/ismart-mqtt-gateway.jar"] 
```
